version: 0.2
phases:
  build:
    commands:
      - echo "Uploading templates to S3..."
      - aws s3 cp cf-templates/ s3://$ARTIFACT_BUCKET/cf-templates/ --recursive
artifacts:
  files:
    - cf-templates/*
