AWSTemplateFormatVersion: "2010-09-09"
Description: Master Stack for VPC + RDS Setup

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC

  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for the first public subnet

  PublicSubnet2CIDR:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for the second public subnet
  
  PrivateSubnet1CIDR:
    Type: String
    Default: 10.0.3.0/24
    Description: CIDR block for the first private subnet

  PrivateSubnet2CIDR:
    Type: String
    Default: 10.0.4.0/24
    Description: CIDR block for the second private subnet
  
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 KeyPair for SSH access
  
  CodeStarConnectionArn:
    Type: String
    Description: ARN of CodeStar Connection (for GitHub)
  
  GitHubRepoBE:
    Type: String
    Description: GitHub repository in the format owner/repo for BE Setup

  GitHubBranchBE:
    Type: String
    Default: main
  
  JwtSecretKey:
    Type: String
    Default: supersecretjwtkey
  
  GitHubRepoFE:
    Type: String
    Description: GitHub repository in the format owner/repo for FE Setup

  GitHubBranchFE:
    Type: String
    Default: main
  
  SubscriberEmail:
    Type: String
    Description: Email address to subscribe to SNS topic
  
  UseAuroraForDB:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: "Set to true to deploy Aurora DB instead of standard RDS"


Conditions:
  UseAurora: !Equals [!Ref UseAuroraForDB, "true"]
  UseRDS: !Equals [!Ref UseAuroraForDB, "false"]
    

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://lms-all-stacks.s3.ap-south-1.amazonaws.com/3.LMS-All-Templates/2.VPC-Setup.yml
      Parameters:
        VpcCIDR : !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
      TimeoutInMinutes: 10

  # RDS Stack with MySql
  RDSStack:
    Condition: UseRDS
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://lms-all-stacks.s3.ap-south-1.amazonaws.com/3.LMS-All-Templates/3.RDS-Setup.yml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        Subnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        Subnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        PasswordLambdaRole: !GetAtt IAMRolesStack.Outputs.PasswordLambdaRole
      TimeoutInMinutes: 15
  
  # RDS For Aurora
  AuroraStack:
    Condition: UseAurora
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://lms-all-stacks.s3.ap-south-1.amazonaws.com/3.LMS-All-Templates/6.RDS-Aurora.yml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        Subnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        Subnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        PasswordLambdaRole: !GetAtt IAMRolesStack.Outputs.PasswordLambdaRole
      TimeoutInMinutes: 15

  # IAM Roles Stack
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://lms-all-stacks.s3.ap-south-1.amazonaws.com/3.LMS-All-Templates/7.IAM-Stack.yml
      Parameters:
        CodeStarConnectionArn: !Ref CodeStarConnectionArn
      TimeoutInMinutes: 10
  
  # BE Stack with CI/CD
  BackendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://lms-all-stacks.s3.ap-south-1.amazonaws.com/3.LMS-All-Templates/4.BE-Setup.yml
      Parameters:
        InstanceType: t2.micro
        VpcId: !GetAtt VPCStack.Outputs.VpcId 
        PublicSubnets: 
          Fn::Join:
            - ","              # delimiter
            -                  # list starts here
              - !GetAtt VPCStack.Outputs.PublicSubnet1
              - !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnets: 
          Fn::Join:
            - ","              # delimiter
            -                  # list starts here
              - !GetAtt VPCStack.Outputs.PrivateSubnet1
              - !GetAtt VPCStack.Outputs.PrivateSubnet2
        CodeStarConnectionArn: !Ref CodeStarConnectionArn 
        GitHubRepo: !Ref GitHubRepoBE
        GitHubBranch: !Ref GitHubBranchBE
        JwtSecret: !Ref JwtSecretKey 
        RDSStackName: !If
          - UseAurora
          - !GetAtt AuroraStack.Outputs.RDSSecurityGroupId
          - !GetAtt RDSStack.Outputs.RDSSecurityGroupId
        KeyName : !Ref KeyName
        AlarmEmail: !Ref SubscriberEmail
        CodeBuildRole: !GetAtt IAMRolesStack.Outputs.BECodeBuildRole
        CodeDeployServiceRole: !GetAtt IAMRolesStack.Outputs.BECodeDeployServiceRole
        CodePipelineRole: !GetAtt IAMRolesStack.Outputs.BECodePipelineRole
        EC2InstanceProfileName: !GetAtt IAMRolesStack.Outputs.EC2InstanceProfile
      TimeoutInMinutes: 10
  
  # FE Stack with CI/CD
  FrontendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: BackendStack
    Properties:
      TemplateURL: https://lms-all-stacks.s3.ap-south-1.amazonaws.com/3.LMS-All-Templates/5.FE-Setup.yml
      Parameters:
        CodeStarConnectionArn: !Ref CodeStarConnectionArn 
        GitHubRepo: !Ref GitHubRepoFE
        GitHubBranch: !Ref GitHubBranchFE
        BackendURL: !GetAtt BackendStack.Outputs.BackendCloudFrontURL
        InvalidateCloudFrontLambdaRole: !GetAtt IAMRolesStack.Outputs.InvalidateCloudFrontLambdaRole
      TimeoutInMinutes: 10

Outputs:
  RDSInstanceEndpoint:
    Description: RDS instance EndPoint
    Value: !If
      - UseAurora
      - !GetAtt AuroraStack.Outputs.DBEndpoint
      - !GetAtt RDSStack.Outputs.DBEndpoint

  BackendURL:
    Description: Back end URL Info
    Value: !GetAtt BackendStack.Outputs.BackendCloudFrontURL

  FrontendURL:
    Description: Front end URL Info
    Value: !GetAtt FrontendStack.Outputs.CloudFrontURL
