AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to launch an EC2 with Mapping Values

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to SSH into the instance
    Type: AWS::EC2::KeyPair::KeyName
  InstanceName:
    Type: String
    Default: Test

Mappings:
    RegionMap:
      us-east-1:
          AMI: ami-0de716d6197524dd9
      us-west-1:
          AMI: ami-01776cde0c6f0677c
      ap-south-1:
          AMI: ami-0144277607031eca2

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  DemoInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region",AMI] 
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: !Ref InstanceName
      UserData:
        Fn::Base64: | 
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          echo "<h1>Hello from $(hostname -f)</h1>" > /var/www/html/index.html

Outputs:
  InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref DemoInstance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt DemoInstance.PublicIp
