AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD Pipeline for Infrastructure Templates (CloudFormation)

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub Repository in format <owner>/<repo>
  BranchName:
    Type: String
    Default: main
    Description: Branch to trigger pipeline from
  ConnectionArn:
    Type: String
    Description: ARN of CodeStar Connection to GitHub
  KeyName:
    Description: Name of an existing EC2 KeyPair to SSH into the instance
    Type: AWS::EC2::KeyPair::KeyName
  InstanceName:
    Type: String
    Default: DemoInstance

Resources:
  ## S3 bucket for pipeline artifacts
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  ## IAM Role assumed by CloudFormation during deploy
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ## IAM Role for CodePipeline
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipelineExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ## CodePipeline
  InfraPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref GitHubRepo
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Deploy
          Actions:
            - Name: CFNDeployMaster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MasterStack
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: SourceOutput::infra-ci-cd/master.yml
                RoleArn: !GetAtt CloudFormationRole.Arn
                ParameterOverrides: !Sub '{"KeyName":"${KeyName}","InstanceName":"${InstanceName}"},"ArtifactBucket":"${ArtifactBucket}"'
              InputArtifacts:
                - Name: SourceOutput

Outputs:
  PipelineName:
    Description: Name of the Infra Pipeline
    Value: !Ref InfraPipeline
  ArtifactBucketName:
    Description: S3 Bucket for Artifacts
    Value: !Ref ArtifactBucket
