AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD Pipeline for Infrastructure Templates (CloudFormation)

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub Repository in format <owner>/<repo>
  BranchName:
    Type: String
    Default: main
    Description: Branch to trigger pipeline from
  ConnectionArn:
    Type: String
    Description: ARN of CodeStar Connection to GitHub
  KeyName:
    Description: Name of an existing EC2 KeyPair to SSH into the instance
    Type: AWS::EC2::KeyPair::KeyName
  InstanceName:
    Type: String
    Default: DemoInstance

Resources:
  ## S3 bucket for pipeline artifacts
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  ## IAM Role assumed by CloudFormation during deploy
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationDeployPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Read from artifacts bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: !Sub "${ArtifactBucket.Arn}/*"
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !GetAtt ArtifactBucket.Arn

              # EC2 permissions
              - Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:TerminateInstances
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:Describe*
                Resource: "*"

              # Allow CloudFormation to pass instance profiles if needed
              - Effect: Allow
                Action: iam:PassRole
                Resource: "arn:aws:iam::${AWS::AccountId}:role/*"
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - ec2.amazonaws.com

  ## IAM Role for CodePipeline
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipelineExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Artifacts
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: !Sub "${ArtifactBucket.Arn}/*"
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !GetAtt ArtifactBucket.Arn

              # Use CodeStar connection
              - Effect: Allow
                Action: codestar-connections:UseConnection
                Resource: !Ref ConnectionArn

              # Allow pipeline to manage CloudFormation stacks
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplate
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                Resource: "*"

              # Critical fix: Allow CodePipeline to pass CloudFormationRole
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt CloudFormationRole.Arn
                Condition:
                  StringEquals:
                    iam:PassedToService: cloudformation.amazonaws.com

  ## CodePipeline
  InfraPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref GitHubRepo
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Deploy
          Actions:
            - Name: CFNDeployMaster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MasterStack
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: SourceOutput::infra-ci-cd/master.yml
                RoleArn: !GetAtt CloudFormationRole.Arn
                ParameterOverrides: !Sub '{"KeyName":"${KeyName}","InstanceName":"${InstanceName}"}'
              InputArtifacts:
                - Name: SourceOutput

Outputs:
  PipelineName:
    Description: Name of the Infra Pipeline
    Value: !Ref InfraPipeline
  ArtifactBucketName:
    Description: S3 Bucket for Artifacts
    Value: !Ref ArtifactBucket
